version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run lint
            - run: npm run build

  publish:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
            - run: npm run lint
            - run: npm run build
            - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && npm publish

workflows:
  test:
    jobs:
      - test
      - publish:
          filters:
            branches:
              only: master

